version: "3.4"

services:
   mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-container
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    volumes:
      - /mongodb_data_container/_data
    ports:
      - 8002:8081
    
networks:
  default:
   external:
    name: mydockernetwork
